Document: waylandpp
Title: Debian waylandpp Manual
Author: <insert document author here>
Abstract: This manual describes what waylandpp is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/waylandpp/waylandpp.sgml.gz

Format: postscript
Files: /usr/share/doc/waylandpp/waylandpp.ps.gz

Format: text
Files: /usr/share/doc/waylandpp/waylandpp.text.gz

Format: HTML
Index: /usr/share/doc/waylandpp/html/index.html
Files: /usr/share/doc/waylandpp/html/*.html
